### ISSUE TITLE
Reaction and suggestion

### ISSUE THREAD

**Issue by Eianex** [rebane2001/aimobs#6]
Hello Rebane,

I have tested your AI mod and it is epic. I also have ported the mod to a Spanish Translated Version and it works pretty well.
One quick question that I have is if I could use this mod somehow with _**fabric-api-0.63.0+1.19.2**_ or if it is completely impossible? as some of the other mods I have require a little more antique version of fabric api.
Also, the text model from OpenAI asks you continously if you need something, and when you tell a villager to collect some wood for you, then obviously he tells you that he will collect it, but finally does not because villagers dont have that ability. Do you have some possible easy solution for this? Or this implementation is very fantasy-hard and it can not be implemented?

Thanks for the good work and keep up with the project mate.

**Comment by rebane2001** [comment]
There's a 1.19.2 branch available

**Comment by Eianex** [comment]
Correct, the only issue is that when used with other mods and fabric 63, the command /aimobs doesnt work.

**Comment by makarikk** [comment]
Sorry, could you tell me how you ported the mod to another language?

**Comment by Eianex** [comment]
> Sorry, could you tell me how you ported the mod to another language?

Suposing you have installed on your PC both Git and Java-17-sdk, do the following:

1. Create any folder, lets say "ai-test"
2. inside that folder open the terminal cmd
3. `git init`
4. `git clone https://github.com/rebane2001/aimobs.git`
5. `cd aimobs`
6. go to the file `src/main/java/com/rebane2001/aimobs/ActionHandler.java`
7. open it with any code editor, I use VScode
8. change all english phrases to the language you want, example: "Your friend" to: "Tu amigo"
9. once you finished translating, save the file and in your terminal that you still have open type
10. `gradlew build`
11. your new .jar file will be inside folder `libs`

**Comment by makarikk** [comment]
Hello, I'm the person who asked about porting aimobs to another language.

I'm a YouTuber from Ukraine and I want to make a video about this mod.
Thank you so much for your help, I will definitely try this. But didn't
quite understand why change the code, because when you call a mob in any
language, it responds in it. 
But there is one problem: The mod works
properly, but when the animal speaks English or Spanish and any similar
language, then everything goes fine. But if you turn to an animal in a
language that is written in Cyrillic, such as Ukrainian or Russian, then
the answer will be interrupted in half. That is, the message simply will
not be complete, after about 7-12 words it simply breaks off. I checked
many launchers, ran it on different computers but it didn't help. I
concluded that the problem is in the mod, maybe I need to change the mode
using the setmode command, but none of the ones I know of work. 

Perhaps you know how to fix the problem? I noticed that you understand mods, and
perhaps you know what the problem is. I'm sorry for disturbing you.


нд, 7 трав. 2023 р. о 19:13 Tony Stark ***@***.***> пише:

**Comment by Eianex** [comment]
No problem, I was born in Ukraine too, we can chat in discord if you want. In order to not spam the issue line here on github. `Eianex#8252` . Anyways, if the message is cut in half is not problem of the cirilic. In spanish and english if the answer is too long it cuts itself too. There is a parameter in the code that we can modify to make the answer longer. But again, if you want us to port the mod to ukranian I would be glad to help, but let's do it over discord. Also, I don't think the best idea is to "longer" the output, because by default it uses gpt 3 model, which is not very good, the user will spend money on a not very good language model, it would be better if we can implement 3.5 turbo or even 4.0.

**Comment by makarikk** [comment]
Wow, that would be incredible. I sent you a request!

нд, 7 трав. 2023 р. о 21:14 Tony Stark ***@***.***> пише:

**Comment by Eianex** [comment]
Completely using fabric 1.19.4 now and created branches and releases for english, spanish and ukranian mod. [Click here for checking out releases](https://github.com/Eianex/aimobs/releases). Closing this line.
